name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Azure Cosmos DB Emulator
      uses: southpolesteve/cosmos-emulator-github-action@v1
    
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: 'Start-CosmosDbEmulator /EnableTableEndpoint'

    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: 'Start-CosmosDbEmulator /EnableMongoDbEndpoint=3.6'
      
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
